### ISSUE TITLE
Support environment variables / vault keys anywhere

### ISSUE THREAD

**Issue by moshloop** [flanksource/platform-cli#134]
Currently, environment variables are manually templatized for specific fields in https://github.com/flanksource/platform-cli/blob/master/cmd/common.go#L80 - this should be dynamic and work on any spec field.

With time we want to extend support from just environment variables, to vault keys and potentially K8s secrets as well.

**Comment by moshloop** [comment]
Switch to custom string type with a custom YAML unmarshall that supports local files, go-getter files, $ENV vars, commons/text.Template, and vault paths

**Comment by teodor-pripoae** [comment]
Closed by #216
