### ISSUE TITLE
Add Kubernetes auditing support

### ISSUE THREAD

**Issue by moshloop** [flanksource/platform-cli#57]
e.g. https://github.com/ministryofjustice/cloud-platform-infrastructure/blob/master/kops/cloud-platform-live-0.yaml#L10

**Comment by philipstaffordwood** [comment]
Above link is stale, this references the commit:
https://github.com/ministryofjustice/cloud-platform-infrastructure/blob/5ba609418a601da4bee30cf2c794edd79388685c/kops/cloud-platform-live-0.yaml#L10

**Comment by philipstaffordwood** [comment]
working in this fork and branch[philipstaffordwood/platform-cli issue-57-k8s-auditing-support](https://github.com/philipstaffordwood/platform-cli/tree/issue-57-k8s-auditing-support)
