### ISSUE TITLE
NodeLocalDNS  CrashLooping

### ISSUE THREAD

**Issue by moshloop** [flanksource/platform-cli#66]

**Comment by mazzy89** [comment]
The reason why it does not work this is that Node Local DNS manifest requires some configuration that must be changed before pushing the manifest to the cluster. 

In the `ConfigMap` there are some placeholders like this `__PILLAR__DNS__DOMAIN__` that require specific cluster values to be changed.

The following variables require proper substitution during the bootstrap phase.

__PILLAR__DNS__SERVER__ - set to kube-dns service IP.
__PILLAR__LOCAL__DNS__ - set to the link-local IP(169.254.20.10 by default).
__PILLAR__DNS__DOMAIN__ - set to the cluster domain(cluster.local by default).

@moshloop The manifest is installed along with the other manifest in the phase `base`. I assume that in that phase the cluster is already up so we can query it for some configuration value. Did I get it correctly?

**Comment by moshloop** [comment]
Correct during base deployment the cluster will be up and we can query it for the values and then replace them with golang template which will automatically be applied using ApplySpecs.

```golang
platform.NodeLocalDNS.DNSServer = "x.x.x.x"
```
And then in the template use: 
```
{{.nodeLocalDNS.dnsServe}}
```

**Comment by moshloop** [comment]
confirmed fixed
